project:
  type: website

website:
  title: "Tyler Hillery"
  site-url: https://www.tylerhillery.com
  description: "Personal website where I share my thoughts, ideas and projects."
  favicon: assets/images/favicon.ico
  image: assets/images/profile2.jpg
  repo-url: https://github.com/TylerHillery/tylerhillery.com
  repo-actions: [edit, issue]

  comments:
    giscus:
      repo: TylerHillery/tylerhillery.com
  navbar:
    left:
      - href: blog.qmd
        text: Blog
      - href: notes.qmd
        text: Notes
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/TylerHillery
      - icon: linkedin
        href: https://www.linkedin.com/in/tylerhillery/
      - icon: twitter
        href: https://twitter.com/_TylerHillery
      - icon: book
        href: https://www.goodreads.com/user/show/150025597-tyler-hillery
      - icon: rss
        href: blog.xml
format:
  html:
    theme: custom.scss
    toc: true
    toc-location: left
    smooth-scroll: true
    code-line-numbers: true
    highlight-style: atom-one
execute:
  freeze: auto
resources:
  - CNAME
